<div class="data">
  <h1>Privacy Policy</h1>


  <p>At our calculator tools website, we take your privacy very seriously. We are committed to protecting your personal information and ensuring that it is used only for its intended purposes. This privacy policy outlines how we collect, use, and disclose your personal information when you use our calculator tools website.

  </p>
  <p>Information we collect: When you use our calculator tools website, we may collect personal information such as your name, email address, and other contact information. We may also collect non-personal information such as your IP address, browser type, and operating system.

  </p>
  <p>Use of information: We use the information we collect to provide you with our calculator tools and services, to communicate with you, and to improve our website and services. We do not sell or rent your personal information to third parties.

  </p>
  <p>Cookies: Our website uses cookies to enhance your user experience and to collect non-personal information about your use of our website. You can disable cookies in your browser settings if you do not wish to have them stored on your computer.

  </p>
  <p>Disclosure of information: We may disclose your personal information to third-party service providers who assist us in providing our calculator tools and services. We may also disclose your personal information if required by law or to protect our rights or the safety of others.

  </p>
  <p>Security: We take reasonable measures to protect your personal information from unauthorized access, use, or disclosure. However, no method of transmission over the internet or electronic storage is completely secure, and we cannot guarantee the security of your information.

  </p>
  <p>Children's privacy: Our website is not intended for use by children under the age of 13. We do not knowingly collect personal information from children under the age of 13.

  </p>
  <p>Changes to this policy: We may update this privacy policy from time to time. Any changes will be posted on our website, and your continued use of our website after such changes are made will constitute your acceptance of the revised policy.

  </p>
  <p>By using our calculator tools website, you consent to the collection, use, and disclosure of your personal information as described in this privacy policy. If you have any questions or concerns about our privacy policy, please contact us.
  </p>

</div>