<style>
  .font10 {
    font-size: 10px;
}

.font11 {
    font-size: 11px;
}

.font12 {
    font-size: 12px;
}

.font13 {
    font-size: 13px;
}

.font14 {
    font-size: 14px;
}

.font15 {
    font-size: 15px;
}
.font16 {
    font-size: 16px;
}
.font18 {
    font-size: 18px;
}

.font22 {
    font-size: 22px;
}

.font-w500 {
    font-weight: 500;
}

.font-w900 {
    font-weight: 900;
}

.font-n {
    font-weight: normal;
}

.font-b {
    font-weight: bold;
}
.font_s-n {
    font-style: normal;
}
.p-0 {
    padding: 0;
}

.p-10 {
    padding: 10px;
}
.p-12 {
    padding: 12px;
}
.p15 {
    padding: 15px;
}
.p-20 {
    padding: 20px;
}

.pt-0 {
    padding-top: 0;
}
.pt-10 {
    padding-top: 10px;
}
.pt-20 {
    padding-top: 20px;
}
.pt-25 {
    padding-top: 25px;
}
.pb-0 {
    padding-bottom: 0;
}

.pb-5 {
    padding-bottom: 5px;
}

.pb-10 {
    padding-bottom: 10px;
}

.pb-15 {
    padding-bottom: 15px;
}

.pl-0 {
    padding-left: 0;
}

.pl-5 {
    padding-left: 5px;
}

.pl-8 {
    padding-left: 8px;
}

.pl-10 {
    padding-left: 10px;
}

.pl-15 {
    padding-left: 15px;
}

.pr-0 {
    padding-right: 0;
}

.pr-5 {
    padding-right: 5px;
}

.pr-8 {
    padding-right: 8px;
}

.pr-10 {
    padding-right: 10px;
}

.pr-15 {
    padding-right: 15px;
}

.ptb-0 {
    padding-top: 0;
    padding-bottom: 0;
}

.ptb-5 {
    padding-top: 5px;
    padding-bottom: 5px;
}

.ptb-10 {
    padding-top: 10px;
    padding-bottom: 10px;
}
.ptb-12{
    padding-top: 12px;
    padding-bottom: 12px;
}
.ptb-15 {
    padding-top: 15px;
    padding-bottom: 15px;
}

.prl-0 {
    padding-right: 0;
    padding-left: 0;
}

.prl-5 {
    padding-right: 8px;
    padding-left: 8px;
}

.prl-8 {
    padding-right: 5px;
    padding-left: 5px;
}

.prl-10 {
    padding-right: 10px;
    padding-left: 10px;
}

.prl-15 {
    padding-right: 15px;
    padding-left: 15px;
}
.prl-20 {
    padding-right: 20px;
    padding-left: 20px;
}

.m-0 {
    margin: 0;
}

.m-5 {
    margin: 5px;
}

.m-10 {
    margin: 10px;
}

.m-15 {
    margin: 15px;
}

.mb-30 {
    margin-bottom: 2rem;
}

.mb-50 {
    margin-bottom: 3rem;
}

.mt-0 {
    margin-top: 0;
}

.mt-5 {
    margin-top: 5px;
}

.mt-8 {
    margin-top: 8px;
}

.mt-10 {
    margin-top: 10px;
}

.mt-15 {
    margin-top: 15px;
}
.mt-20 {
    margin-top: 20px;
}

.mt-50 {
    margin-top: 50px;
}

.mb-0 {
    margin-bottom: 0;
}

.mb-5 {
    margin-bottom: 5px;
}

.mb-8 {
    margin-bottom: 8px;
}

.mb-10 {
    margin-bottom: 0.63rem;
}

.mb-16 {
    margin-bottom: 1rem;
}

.ml-0 {
    margin-left: 0;
}

.ml-5 {
    margin-left: 5px;
}

.ml-10 {
    margin-left: 10px;
}

.ml-15 {
    margin-left: 15px;
}
.mr-auto {
    margin-right:auto;
}
.mr-0 {
    margin-right: 0;
}

.mr-5 {
    margin-right: 5px;
}

.mr-10 {
    margin-right: 10px;
}

.mr-15 {
    margin-right: 15px;
}

.mtb-0 {
    margin-top: 0;
    margin-bottom: 0;
}

.mtb-5 {
    margin-top: 5px;
    margin-bottom: 5px;
}



.tcenter {
    text-align: center;
}
.posrel{position:relative;}
.bgwht{background-color: white;}

.bg_color{background-color: antiquewhite;height: 30px;}

.height100p{height:100%;}

.chngp.up {
    background-color: #17b978;
    padding: 0 7px;
    display: inline-block;
    border-radius: 4px;
    font-size: 13px;
    height: 25px;
    line-height: 26px;
    color: #fff;
    white-space: nowrap;
}
.th-left {
  float: left;
  padding-top: 8px;
  padding-left: 10px;
}
.col3 {
    width: 33.33%;
  }
  #container {
    column-count: 3;
    -moz-column-count: 3;
    -webkit-column-count: 3;
    width: 100%;
}
.item {
    display: inline-block;    
    margin-bottom: 20px;
    width: 100%;
}
table tr td {
  height: 40px;
}
</style>
<div class="data">
 <?php include $this->template_dir . 'home.phtml';?> 
  <div>
    <section class="p15 mt-10">
      <h3 class="font18 tcenter mb-16">List Of Post Offices For <?php echo $this->pincode ?> </h3>
      <div class="tabs_cont">
        <div class="bgwht posrel">
          <div class="tb-data-con">

            <div class="overflow-hidden">
              <table width="100%" class="font16 " border="0" cellspacing="0" cellpadding="0">
                <tbody>
                  <tr class="bg_color">
                    <th class="th-left">Post Office</th>
                    <th >District</th>
                    <th >State</th>
                    
                  </tr>
                  <?php foreach($this->officeLists as $officeLists){ $url= BASE_URL_BASE.'/pincodedetails/'.$officeLists['url'];?>
                  <tr>
                    <td class="th-left"><a><?php echo $officeLists['office_name']; ?></a></td>
                    <td><?php echo $officeLists['district']; ?></td>
                    <td><?php echo $officeLists['circle_name']; ?></td>
                  </tr>
                                 
                  <?php } ?>
                  </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>