<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="<?php echo $this->meta_tags['description'];?>">
  <meta name="author" content="">

  <title><?php echo $this->meta_tags['title'];?></title>

  <!-- Bootstrap core CSS -->
  <style>
    .table-responsive {
      display: inline-table;
    }

    .pnr-s-bt {
      float: right;
      padding-left: 348px;
    }

    .nodisplay {
      display: none;
    }

    ins.adsbygoogle[data-ad-status="unfilled"] {
      display: none !important;
    }

    .gads_web {
      display: block;
    }

    @media (max-width: 767px) {
      .gads_web {
        display: none;
      }

      .gads_wap {
        display: block;
      }

      .table-responsive {
        display: inline;
      }

      .pnr-s-bt {
        float: none;
        padding-left: 14px;
        padding-top: 50px;
      }
    }


    .pnr .table thead th {
      color: #fff;
    }
  </style>
  <!-- Additional CSS Files -->
  <link rel="stylesheet" href="<?php echo CDN_URL; ?>/css/style.css?v5">

  <script async src="https://www.googletagmanager.com/gtag/js?id=G-EMMME9W321"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());
    gtag('config', 'G-EMMME9W321');
  </script>
  <!--
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6006321074543405" crossorigin="anonymous"></script>
  -->  
</head>

<body>

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky background-header">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
            <!-- ***** Logo Start ***** -->
            <a href="<?php echo BASE_URL; ?>" class="logo" aria-label="Home"></a>
            <!-- ***** Logo End ***** -->
            <!-- ***** Menu Start ***** -->
            <ul class="nav">
              <li><a href="<?php echo BASE_URL; ?>" class="active">Home</a></li>
              <li><a href="<?php echo BASE_URL; ?>/salary-hike-percentage">Salary Hike Calculator</a></li>
              <li><a href="<?php echo BASE_URL; ?>/indian-railways/pnr-status">PNR Status</a></li>
              <li><a href="<?php echo BASE_URL; ?>/indian-railways/live-train-status">Train Running Status</a></li>
              <li><a href="<?php echo BASE_URL; ?>/fuel-price">Fuel Price</a></li>
             
              <li><a href="<?php echo BASE_URL; ?>/about-us">About Us</a></li>

            </ul>
            <a class="menu-trigger" href="<?php echo BASE_URL; ?>">
              <span>Menu</span>
            </a>

            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

  <div class="main-banner">
    <!--WEB-->
    <ins class="adsbygoogle nodisplay gads_web" data-ad-client="ca-pub-6006321074543405" data-ad-slot="6029207754" data-ad-format="auto" data-full-width-responsive="true">
    </ins>
    <!--WAP-->
    <ins class="adsbygoogle nodisplay gads_wap" data-ad-client="ca-pub-6006321074543405" data-ad-slot="1627477056" data-ad-format="auto" data-full-width-responsive="true">
    </ins>
    <div class="container">
      <div class="main-banner">
        <?php include_once $this->template_dir . $template_file; ?>
      </div>
    </div>
  </div>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="about">
            <div class="logo">
              <img src="<?php echo CDN_URL; ?>/images/logo-small.png" alt="FREE BEST TOOLS" width="163" height="32">
            </div>
            <h2>About Us</h2>
            <p>If you're looking for reliable calculator tools to help you solve complex equations or make quick computations, you've come to the right place. Our collection of calculator tools is designed to provide you with accurate results in no time, so you can save time and focus on other important tasks.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="helpful-links">
          <h2>Helpful Links</h2>
            <div class="row">
              <div class="col-lg-6 col-sm-6">
                <ul>
                  <li><a href="<?php echo BASE_URL; ?>/salary-hike-percentage">Salary Hike Percentage</a></li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul>
                  <li><a href="<?php echo BASE_URL; ?>/about-us">About Us</a></li>
                  <li><a href="<?php echo BASE_URL; ?>/privacy-policy">Privacy Policy</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="contact-us">
            <h2>Contact Us</h2>
            <p>free-best-tools@gmail.com</p>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="sub-footer">
            <p>Copyright © <?php echo date('Y'); ?> free-best-tools.com. All Rights Reserved.</p>
          </div>
        </div>
      </div>
    </div>
  </footer>


  <!-- Scripts -->
  
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>

  <script defer src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
  <script defer src="<?php echo CDN_URL; ?>/js/custom.js?v2"></script>
</body>

</html>