<div class="main-banner">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="top-text header-text">
            <h6>PNR Status</h6>
           
          </div>
           
        </div>
        <div class="col-lg-12">
          <!--<form id="search-form" name="gs" method="submit" role="search" action="#">-->
          <form id="search-form" name='pnrForm' method="POST" action="">

            <div class="row pnr-form">
            <?php if($this->pnrErr!=''){?>
                <div class="col-lg-12" style="color:red;"><?php  echo $this->pnrErr;?></div>
              <?php } ?>
              
              <div class="col-lg-6 align-self-center">
                  <fieldset>
                      <input type="text" name='pnr' maxlength="10" onkeypress='return ((event.charCode >= 48 && event.charCode <= 57) ||  event.charCode == 0)' id='pnr' value='<?php  echo $this->pnr;?>'  placeholder="Enter PNR no."  required=""/>
                  </fieldset>
              </div>               
              
              <div class="col-lg-6">                        
                  <fieldset>
                     
                      <div class="main-button" ><input type='submit' name='submit' value='PNR Status' id='pnrSumbit' style="border:1px solid red !important; background-color: lightseagreen" /></div>
                      <!--<button class="main-button"><i class="fa fa-search"></i> Calculate</button>-->
                  </fieldset>
              </div>
            </div>
          </form>
        </div>
       
      </div>
    </div>
  </div>