<div class="main-banner">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="top-text header-text">
            <h1>Gratuity Calculator</h1>
          </div>
            <?php if($this->gratuity!=''){?>
            <div class="top-text header-text"><h2><span style='color:green'><?php  echo $this->gratuity;?></span></h2></div>
          <?php } ?>
        </div>
        <div class="col-lg-12">
          <form id="search-form" name='calForm' method="POST" action="">

            <div class="row">
              
              <div class="col-lg-3 align-self-center">
                  <fieldset>
                      <!--<input type="address" name="address" class="searchText" placeholder="Enter a location" autocomplete="on" required="">-->
                      <input type="number" name='basic' id='basic' value='<?php  echo $this->basic;?>'  placeholder="BASIC SALARY"  required="" />
                  </fieldset>
              </div>
                 <?php if($this->basicErr!=''){?>
                <div style="color:red;"><?php  echo $this->basicErr;?></div>
                <?php } ?>
              <div class="col-lg-3 align-self-center">
                  <fieldset>
                      <input type="number" name='tenure' value='<?php  echo $this->tenure;?>' placeholder="Tenure in number of years" required=""/>
                  </fieldset>
                  
              </div>
                <?php if($this->tenureErr!=''){?>
                <div style="color:red;"><?php  echo $this->tenureErr;?></div>
                <?php } ?>
              <div class="col-lg-6">                        
                  <fieldset>
                     
                      <div class="main-button" ><input type='submit' name='submit' value='Get Your Gratuity' id='clacSumbit' style="border:1px solid red !important; background-color: lightseagreen" /></div>
                      <!--<button class="main-button"><i class="fa fa-search"></i> Calculate</button>-->
                  </fieldset>
              </div>
            </div>
          </form>
        </div>
       
      </div>
    </div>
  </div>